# Generated by Django 4.2 on 2023-04-18 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_delete_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
