# Generated by Django 4.2 on 2023-04-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('management_company', 'Управляющая компания'), ('user', 'Пользователь'), ('super_admin', 'Супер админ'), ('executor', 'Исполнитель'), ('customer', 'Заказчик'), ('auditor', 'Аудитор')], default='user', max_length=20),
        ),
    ]
