# Generated by Django 4.2 on 2023-04-20 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_executor'),
        ('order', '0005_order_count_order_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='product.product'),
        ),
    ]
